name: Test

on: ['pull_request', 'push']

jobs:
  pest:
    name: Pest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Run Pest
        run: vendor/bin/pest
  phpcs:
    name: PHP Coding Standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Run phpcs
        run: vendor/bin/phpcs
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Run PHPStan
        run: vendor/bin/phpstan
